### DISCUSSION TITLE
Firefox Deployment inside a CasaOS in Single click @ Yesbhautik

### DISCUSSION THREAD

**Discussion by yesbhautik** [IceWhaleTech/CasaOS#1027] [Show and tell]
Step 1: Download the [.json file](https://go.yesbhautik.co.in/WhiteVioletMammoth) | OR | Make .json file with below code snippet
Step 2: Go to AppStore
Step 3: Click on Custom Install
Step 4: Click on import (top right corner | left side of the close button)
Step 5: Click on AppFile
Step 6: Upload .json file
Step 7: Click on Install (You can change the port)

Now, you can open your Firefox: localhost:3456 or ipv4:3456 (this is the default port)

![image](https://user-images.githubusercontent.com/63995315/234703617-3d1704e0-0b7e-4b99-9ea5-bfbf5db0e5bb.png)

`{"host":"","protocol":"http","port_map":"3456","cpu_shares":90,"restart":"unless-stopped","label":"firefox","position":false,"index":"","icon":"https://play-lh.googleusercontent.com/zqsuwFUBwKRcGOSBinKQCL3JgfvOW49vJphq0ZF32aDgfqmuDyl-fEpx4Lxm4pRr7A=s48-rw","network_model":"firefox_default","image":"ghcr.io/linuxserver/firefox","description":"","origin":"local","ports":[{"container":"3000","host":"3456","protocol":"tcp","desc":"","type":0}],"volumes":[{"container":"/config","host":"/var/lib/docker/volumes/firefox_firefox/_data","type":0,"desc":""}],"envs":[{"container":"PGID","host":"100","desc":"","type":0},{"container":"TZ","host":"America/Denver","desc":"","type":0},{"container":"PUID","host":"1026","desc":"","type":0},{"container":"PATH","host":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","desc":"","type":0},{"container":"HOME","host":"/config","desc":"","type":0},{"container":"TERM","host":"xterm","desc":"","type":0},{"container":"S6_CMD_WAIT_FOR_SERVICES_MAXTIME","host":"0","desc":"","type":0},{"container":"S6_VERBOSITY","host":"1","desc":"","type":0},{"container":"S6_STAGE2_HOOK","host":"/docker-mods","desc":"","type":0},{"container":"DISPLAY","host":":1","desc":"","type":0},{"container":"PERL5LIB","host":"/usr/local/bin","desc":"","type":0},{"container":"OMP_WAIT_POLICY","host":"PASSIVE","desc":"","type":0},{"container":"GOMP_SPINCOUNT","host":"0","desc":"","type":0},{"container":"START_DOCKER","host":"true","desc":"","type":0},{"container":"PULSE_RUNTIME_PATH","host":"/defaults","desc":"","type":0},{"container":"NVIDIA_DRIVER_CAPABILITIES","host":"graphics,compat32,utility","desc":"","type":0},{"container":"LSIO_FIRST_PARTY","host":"true","desc":"","type":0},{"container":"TITLE","host":"Firefox","desc":"","type":0},{"container":"PS1","host":"$(whoami)@$(hostname):$(pwd)\\$ ","desc":"","type":0}],"devices":[],"cap_add":[],"cmd":[],"privileged":false,"host_name":"fab074626d6e","container_name":"firefox","appstore_id":0,"custom_id":"6f8f9aba-1b80-4523-b276-9b927e574f10","enable_upnp":false,"version":"1.0"}`

**Comment by luisangelico** [comment]
I don't see the step 5 (Appfile) 
![image](https://github.com/user-attachments/assets/485e8547-2a88-40db-941f-4ecc9312e141)

**Reply by yang-chang-rui** [reply]
我也是这个问题，它只支持yaml和yml

**Reply by yesbhautik** [reply]
```
version: "3.9"

services:
  firefox:
    image: ghcr.io/linuxserver/firefox
    container_name: firefox
    hostname: fab074626d6e
    restart: unless-stopped

    ports:
      - "3456:3000"

    environment:
      PUID: 1026
      PGID: 100
      TZ: America/Denver
      HOME: /config
      TERM: xterm
      DISPLAY: ":1"
      TITLE: Firefox
      START_DOCKER: "true"
      PULSE_RUNTIME_PATH: /defaults
      NVIDIA_DRIVER_CAPABILITIES: graphics,compat32,utility
      OMP_WAIT_POLICY: PASSIVE
      GOMP_SPINCOUNT: "0"
      S6_CMD_WAIT_FOR_SERVICES_MAXTIME: "0"
      S6_VERBOSITY: "1"
      S6_STAGE2_HOOK: /docker-mods
      LSIO_FIRST_PARTY: "true"
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PERL5LIB: /usr/local/bin
      PS1: '$(whoami)@$(hostname):$(pwd)\$ '

    volumes:
      - /var/lib/docker/volumes/firefox_firefox/_data:/config

    networks:
      - firefox_default

    cpu_shares: 90
    privileged: false

networks:
  firefox_default:
    driver: bridge
```

You can try this
