### DISCUSSION TITLE
[Alpha][Bug] Problems with container update functionality [CasaOS 0.4.4]

### DISCUSSION THREAD

**Discussion by AmadeusGraves** [IceWhaleTech/CasaOS#1158] [General]
### What happened?

There is a problem, now that several applications are supported in the docker compose, the problem is that there may be the case that you only want to update one of the services but it is not possible because you only have the option to update all.

For example:
You have this docker-compose.

```yaml
version: '3'

networks:
  ttrss:

services:
  ttrss:
    image: wangqiru/ttrss
    container_name: ttrss
    restart: always
    environment:
      - SELF_URL_PATH=http://localhost:181
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=ttrss
    ports:
      - "181:80"
    depends_on:
      - db
    networks:
      - ttrss

  db:
    image: postgres
    container_name: ttrss-db
    restart: always
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - ttrss
```

And you only want to update the ttrss app not the database, because if you update the database it may break your app and lost your data. (This happened to me with Nextcloud when I upgraded the postgres database from 14.5 to 15.0 by mistake.)

I think that the only solution is to be able to select the container that you want to update. If the docker compose has 5 services/containers, there should be the possibility that you can select for example 3 containers out of the 5, update them and leave the 2 that are not selected without updating.
