### DISCUSSION TITLE
EmulatorJS: has anyone successfully deployed this yet?

### DISCUSSION THREAD

**Discussion by LilFonky** [IceWhaleTech/CasaOS#1263] [Q&A]
Greetings all-

I'm running CasaOS 0.4.4, and recently tried to deploy EmulatorJS.   The image seems to pull down and something's running, but I'm not getting the typical first run behavior, and don't have any prompts to download the default fileset or any of the other scripted automation detailed in tutorials like this: 

https://www.youtube.com/watch?v=ujDnpn_TCro or this: https://www.youtube.com/watch?v=Zv1cq0JhZfQ&t=345s .

Instead I just get a blank black screen with a button to expand to fullscreen and a folder that take me to what I assume is the admin console.  

- There's a user login to which I have no credentials (and no notes related thereto in the 'TIPS' field inside CasaOS) so I can't  login.
- There's button labeled "Pull Default Config" which grabs nothing but a single .cfg file for Retroarch.  
- There's a Trio of Backup buttons
- There's a button for "Create Folder" which throws a Null Error.
- There's an "Upload Files" button that seems to work well enough.

I get none of the interface elements I expect from watching and reading tutorials on the subject.

So I guess what I'm asking is: has anybody actually made this work?  Is this a problem with the Config on the CasaOS side or is the actual Docker image to blame?

CasaOS-generated .yaml below. Thanks in advance for your insight!

```
name: emulatorjs
services:
  emulatorjs:
    environment:
      - PGID=1000
      - PUID=1000
      - SUBFOLDER=/
      - TZ=Etc/UTC
    image: lscr.io/linuxserver/emulatorjs:1.7.2
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/EmulatorJS/icon.png
    ports:
      - target: 3000
        published: "3001"
        protocol: tcp
      - target: 4001
        published: "4001"
        protocol: tcp
      - target: 80
        published: "88"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/emulatorjs/config
        target: /config
      - type: bind
        source: /DATA/AppData/emulatorjs/data
        target: /data
      - type: bind
        source: /ROMS/nes
        target: /data/nes/roms
    x-casaos:
      ports:
        - container: "80"
          description:
            en_us: Play Game
            zh_cn: 玩游戏
        - container: "3000"
          description:
            en_us: Manage ROMS
            zh_cn: ROM 管理
    devices: []
    cap_add: []
    command: []
    network_mode: bridge
    container_name: ""
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7368M
x-casaos:
  ar_sa: اكتشف قوة المحاكاة مع EmulatorJS - استكشف وتجرب وابتكر عبر أنظمة التشغيل
    وبيئات الأجهزة المتنوعة.
  architectures:
    - amd64
    - arm64
    - arm
  author: self
  category: Utilities
  de_de: Entfesseln Sie die Kraft der Emulation mit EmulatorJS – Erkunden,
    experimentieren und innovieren Sie in vielfältigen Betriebssystemen und
    Geräteumgebungen.
  description:
    ar_sa: EmulatorJS هو تطبيق محاكي يعتمد على Docker يمكنه محاكاة أنظمة التشغيل
      المتعددة وبيئات الأجهزة داخل حاويات لأغراض التطوير والاختبار والتعلم.
    de_de: EmulatorJS ist eine Docker-basierte Emulator-Anwendung, die verschiedene
      Betriebssysteme und Geräteumgebungen in Containern simulieren kann, um für
      Entwicklungs-, Test- und Lernzwecke eingesetzt zu werden.
    en_us: EmulatorJS is a Docker-based emulator application that can simulate
      various operating systems and device environments within containers for
      development, testing, and learning purposes.
    es_es: EmulatorJS es una aplicación de emulador basada en Docker que puede
      simular varios sistemas operativos y entornos de dispositivos dentro de
      contenedores con fines de desarrollo, pruebas y aprendizaje.
    fr_fr: EmulatorJS est une application d'émulation basée sur Docker qui peut
      simuler divers systèmes d'exploitation et environnements de périphériques
      dans des conteneurs à des fins de développement, de test et
      d'apprentissage.
    hu_hu: Az EmulatorJS egy Docker-alapú emulátor alkalmazás, amely konténerekben
      képes szimulálni különböző operációs rendszereket és eszközkörnyezeteket
      fejlesztési, tesztelési és tanulási célokra.
    it_it: EmulatorJS è un'applicazione di emulazione basata su Docker che può
      simulare vari sistemi operativi e ambienti dispositivi all'interno di
      container per scopi di sviluppo, test e apprendimento.
    pl_pl: EmulatorJS to aplikacja emulacyjna oparta na Dockerze, która może
      symulować różne systemy operacyjne i środowiska urządzeń w kontenerach w
      celu rozwoju, testowania i nauki.
    pt_br: EmulatorJS é um aplicativo de emulação baseado em Docker que pode simular
      vários sistemas operacionais e ambientes de dispositivos dentro de
      contêineres para fins de desenvolvimento, teste e aprendizado.
    ru_ru: EmulatorJS - это приложение эмулятора, основанное на Docker, которое
      может моделировать различные операционные системы и среды устройств в
      контейнерах для разработки, тестирования и обучения.
    sv_se: EmulatorJS är en Docker-baserad emulatorapplikation som kan simulera
      olika operativsystem och enhetsmiljöer i containrar för utveckling,
      testning och lärande.
    uk_ua: EmulatorJS - це застосунок емулятора, заснований на Docker, який може
      моделювати різні операційні систем
    zh_cn: EmulatorJS是一个基于Docker的模拟器应用程序，可以在容器中模拟多种操作系统和设备环境，用于开发、测试和学习目的。
  en_us: Unlock the power of emulation with EmulatorJS – Explore, experiment, and
    innovate across diverse operating systems and device environments.
  es_es: Desbloquea el poder de la emulación con EmulatorJS Explora, experimenta e
    innova en diversos sistemas operativos y entornos de dispositivos.
  fr_fr: Libérez la puissance de l'émulation avec EmulatorJS - Explorez,
    expérimentez et innovez dans divers systèmes d'exploitation et
    environnements de périphériques.
  hostname: ""
  hu_hu: Fedezd fel az emuláció erejét az EmulatorJS-szel - Fedezz fel,
    kísérletezz és innoválj sokféle operációs rendszeren és eszközkörnyezetben.
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/EmulatorJS/icon.png
  index: /
  it_it: Sblocca il potere dell'emulazione con EmulatorJS - Esplora, sperimenta e
    innova su diversi sistemi operativi e ambienti dispositivi.
  pl_pl: Odblokuj potęgę emulacji z EmulatorJS - Eksploruj, eksperymentuj i
    innowuj na różnorodnych systemach operacyjnych i środowiskach urządzeń.
  port_map: "88"
  pt_br: Desbloqueie o poder da emulação com o EmulatorJS - Explore, experimente e
    inove em diversos sistemas operacionais e ambientes de dispositivos.
  ru_ru: Разблокируйте мощь эмуляции с помощью EmulatorJS - Исследуйте,
    экспериментируйте и инновируйте в разнообразных операционных системах и
    средах устройств.
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/EmulatorJS/screenshot-1.png
  store_app_id: emulatorjs
  sv_se: Lås upp kraften i emulering med EmulatorJS - Utforska, experimentera och
    innovera över olika operativsystem och enhetsmiljöer.
  tagline: null
  title:
    en_us: emulatorjs
    custom: ""
  uk_ua: Розкрийте потужність емуляції з EmulatorJS - Досліджуйте, експериментуйте
    та інновуйте у різних операційних системах і середовищах пристроїв.
  zh_cn: 发掘模拟的力量，与EmulatorJS一同探索、实验和创新于多样化的操作系统和设备环境。

```
