### DISCUSSION TITLE
Container IP Address

### DISCUSSION THREAD

**Discussion by robsonma1984** [IceWhaleTech/CasaOS#1793] [Q&A]
Hi,
I have installed CasaOs and it all works fine, but I have a group of IP Address that i use for Network management. I want to change the IP Addresses of my Unifi and Pihole so they are in the management range of IP Addresses. 
When i change in the settings i then cant access the Container using the New IP even after a restart.
![Screenshot 2024-04-19 095504](https://github.com/IceWhaleTech/CasaOS/assets/159584231/3c26df61-6a93-4d42-9cfc-aa90f8254718)

I have also tried to change the network to bride, with the same result.
![Screenshot 2024-04-19 095741](https://github.com/IceWhaleTech/CasaOS/assets/159584231/ea34d8ca-1359-499b-8c8b-8805679a1775)

Am i missing something?
Any help would be great.
Thanks

**Comment by Aephir** [comment]
I might be wrong, but I don't think casaOS can set up/manage macvlan networks that are needed to give a container an IP that's __*not*__ just an internal docker IP.

You'd probably need to either create it manually via terminal, something like:

```
docker network create -d macvlan \
  --subnet=192.168.1.0/24 \
  --gateway=192.168.1.1 \
  -o parent=enp2s0 \
  my_macvlan
```

(replace subnet, gateway and interface values is needed). I'm not sure whether you'd also need to deploy other containers via CLI, or if you can choose `my_macvlan` from UI afterwards and specify IP.

Or install Portainer on casaOS, and use that to manage all other apps/containers using stacks (basically docker-compose), so something like:

```
version: '3.7'
services:
  my_container:
    image: linuxserver/unifi-controller
    networks:
      my_macvlan:
        ipv4_address: 192.168.1.126

networks:
  my_macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
```
