### DISCUSSION TITLE
Created Custom Repo With Miniflux in It but Port is Not Working

### DISCUSSION THREAD

**Discussion by TaylanTatli** [IceWhaleTech/CasaOS#1798] [Q&A]
Why is this not working? I managed to install it with Miniflux's compose file successfully with Portainer, but I can't manage to install it in CasaOS. I select a port for it but when I checked it with Portainer there is nothing, and it's keep crashing (Miniflux not database). Here is the [CustomRepo](https://github.com/TaylanTatli/CasaAppRepo) if needed.

```
name: miniflux
services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: "unless-stopped"
    networks:
      - miniflux-network
    depends_on: # Ensure the database service starts before this service
      - miniflux-db
    environment:
      DATABASE_URL: postgres://miniflux:secret/miniflux?sslmode=disable
      ADMIN_PASSWORD: secret
      ADMIN_USERNAME: miniflux
      CREATE_ADMIN: "1"
      RUN_MIGRATIONS: "1"
    ports:
      - target: 8080
        published: "8888"
        protocol: tcp
    container_name: miniflux
  miniflux-db:
    image: postgres:15
    restart: "unless-stopped"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: miniflux
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: miniflux
    container_name: miniflux-db
    networks:
      - miniflux-network
    volumes:
      - type: bind
        source: /DATA/AppData/miniflux/postgresql/data
        target: /var/lib/postgresql/data
networks:
  miniflux-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  author: Frédéric Guillot
  category: TTCasa
  description:
    en_us: "Minimalist and opinionated feed reader"
  developer: Frédéric Guillot
  icon: https://icon.casaos.io/main/all/miniflux.png
  main: miniflux
  port_map: '8888'
  tagline:
    en_us: Minimalist and opinionated feed reader
  title:
    en_us: miniflux
```
