### DISCUSSION TITLE
AFFiNE?

### DISCUSSION THREAD

**Discussion by ronaldohoch** [IceWhaleTech/CasaOS#2160] [Q&A]
Hi guys, has anyone here managed to install AFFiNE on CasaOs?

https://docs.affine.pro/docs/self-host-affine

It has a step-by-step guide, using docker-compose, but I still can't get it to work.
I've been fixing the problems via the container logs, but I haven't been able to get it to connect to Affine's postgres.

edit:

This is my docker-compos with some changes with help of chatgpt:

Docker-compose:
```yml  
name: affine
services:
  affine:
    cpu_shares: 90
    container_name: affine_server
    depends_on:
      affine_migration:
        condition: service_completed_successfully
      affine_postgresql:
        condition: service_healthy
      affine_redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 15907M
    environment:
      - DATABASE_URL=postgresql://affine_user:affine_password@affine_postgresql:5432/affine_db
      - REDIS_SERVER_HOST=affine_redis
    image: ghcr.io/toeverything/affine-graphql:stable
    ports:
      - "3010:3010"
    restart: unless-stopped
    volumes:
      - /mnt/seagate2t/affine/storage:/root/.affine/storage
      - /mnt/seagate2t/affine/config:/root/.affine/config
    networks:
      - affine_network

  affine_migration:
    cpu_shares: 90
    command: ["sh", "-c", "sleep 10 && node ./scripts/self-host-predeploy.js"]
    container_name: affine_migration_job
    depends_on:
      affine_postgresql:
        condition: service_healthy
      affine_redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 15907M
    environment:
      - DATABASE_URL=postgresql://affine_user:affine_password@affine_postgresql:5432/affine_db
      - REDIS_SERVER_HOST=affine_redis
    image: ghcr.io/toeverything/affine-graphql:stable
    restart: unless-stopped
    volumes:
      - /mnt/seagate2t/affine/storage:/root/.affine/storage
      - /mnt/seagate2t/affine/config:/root/.affine/config
    networks:
      - affine_network

  affine_postgresql:
    cpu_shares: 90
    container_name: affine_postgresql
    deploy:
      resources:
        limits:
          memory: 15907M
    environment:
      - POSTGRES_DB=affine_db
      - POSTGRES_USER=affine_user
      - POSTGRES_PASSWORD=affine_password
      - POSTGRES_INITDB_ARGS=--data-checksums
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U affine_user -d affine_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /mnt/seagate2t/affine/db:/var/lib/postgresql/data
    networks:
      - affine_network

  affine_redis:
    cpu_shares: 90
    container_name: affine_redis
    deploy:
      resources:
        limits:
          memory: 15907M
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: redis:latest
    restart: unless-stopped
    networks:
      - affine_network

networks:
  affine_network:
    driver: bridge

```

The log from container:

```
PrismaClientInitializationError: 

Invalid `prisma.runtimeConfig.findMany()` invocation:

Can't reach database server at `affine_postgresql:5432`

Please make sure your database server is running at `affine_postgresql:5432`.

    at $n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7615)

    at $n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:6623)

    at $n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6307)

    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)

    at async Runtime.upgradeDB (file:///app/dist/base/runtime/service.js:194:36)

    at async Runtime.onModuleInit (file:///app/dist/base/runtime/service.js:103:9)

    at async Promise.all (index 0)

    at async callModuleInitHook (/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)

    at async NestApplication.callInitHook (/app/node_modules/@nestjs/core/nest-application-context.js:234:13)

    at async NestApplication.init (/app/node_modules/@nestjs/core/nest-application.js:100:9) {

  clientVersion: '5.22.0',

  errorCode: undefined

}

Node.js v20.18.1
```
