### ISSUE TITLE
[Bug] Docker networks not customizable

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#1156]
**Describe the bug**
Docker containers with more than one application do not have the possibility to modify the network name in the ui and auto-generate one.

**To Reproduce**
1. Go to custom install
2. Click on import
3. Scroll down to paste this docker compose
```yaml
version: '3'

services:
  ttrss:
    image: wangqiru/ttrss
    container_name: ttrss
    restart: always
    environment:
      - SELF_URL_PATH=http://demo.casaos.io:181
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=ttrss
    ports:
      - "181:80"
    depends_on:
      - db

  db:
    image: postgres
    container_name: ttrss-db
    restart: always
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
    volumes:
      - /DATA/AppData/ttrs/db:/var/lib/postgresql/data
```
5. See error
It appears a custom network called "playful_antonio_ttrss" (Capture 1)

**Expected behavior**
Be able to edit the network name

**Screenshots**
Capture 1
![SmartSelect_20230531_215325_Brave](https://github.com/IceWhaleTech/CasaOS/assets/18572939/2e329cc7-5637-48c2-b6a1-12b499a23cf8)

**Desktop (please complete the following information):**
 - CasaOS's demo

**Additional context**
