### ISSUE TITLE
AppStore further adapts container installation (Create Configuration, Customize Pre-installation Parameters)

### ISSUE THREAD

**Issue by Cp0204** [IceWhaleTech/CasaOS#1170]
## Is your feature request related to a problem? Please describe.

目前 AppStore 难以适配某些需要进一步自定义的 Docker 应用，主要体现在两步操作：
Currently, AppStore has difficulty adapting to certain Docker applications that require further customization, which mainly involves two steps:

1. 需预先创建文件  The need to create files in advance. 
2. 自定义安装参数  Custom installation parameters.

例如 For example：
1. [cloudreve](https://docs.cloudreve.org/getting-started/install#docker)  https://github.com/IceWhaleTech/CasaOS-AppStore/issues/52
> 请确保运行之前：手动创建 conf.ini 空文件或者符合 Cloudreve 配置文件规范的 conf.ini, 并将 <path_to_your_config> 替换为该路径

2. [aria2-pro](https://hub.docker.com/r/p3terx/aria2-pro) 设置下载目录和连接密码；
> -e RPC_SECRET=TOKEN
> -v $PWD/aria2-downloads:/downloads

## Describe the solution you'd like

1. 提供复制文件的元数据，这些文件一般不会太大，有可能只是空文件，以防 CasaOS 自动创建为目录；
  Provide metadata for copying files, which are usually not too large and may be empty files to prevent CasaOS from creating them as directories.
```yaml
x-casaos:
  copyfile: 
    - source: conf.ini # In the app directory
      target: /DATA/AppData/$AppID/conf.ini
```

3. 增加自定义安装参数提示  Adding prompts for custom installation parameters.
```yaml
name: aria2-pro
services:
    x-casaos:
      envs:
        - container: RPC_SECRET
          description:
            need-confirm: true
            en_us: RPC secret key setting, which is the password required to be filled in when connecting to the WebUI, and only recommended to use letters and numbers.
            zh_cn: RPC 密钥设置，即 WebUI 连接时需要填写的密码，只建议使用字母和数字。
```

当存在 need-confirm 时，需进一步确认，而非直接安装。
When "need-confirm" exists, further confirmation is required instead of direct installation.

![image](https://github.com/IceWhaleTech/CasaOS/assets/5239753/6c8e6d2b-450a-4333-8318-f8561dc073d7)
