### ISSUE TITLE
[Alpha][Bug] CasaOS 0.4.4, Containers lost conection to internet after restart of the PC

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#1252]
### What happened?

Containers lost connection to internet after restart or power up of the pc. For example, in nextcloud when you go to install a new application, you can't see all the apps of the appstore. 

I notice something strange, if you restart the container in the casaos ui, the container will have access to internet. 

INFO:
OS. Ubuntu 22.04 LTS
Docker version 24.0.2, build cb74dfc
CasaOS 0.4.4

ComposeFile of Nextcloud.

```yaml
name: nextcloud
services:
  nextcloud:
    cpu_shares: 90
    command:
      - apache2-foreground
    container_name: nextcloud
    depends_on:
      nextcloud-db:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=512M
    image: nextcloud:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
    ports:
      - target: 80
        published: "43920"
        protocol: tcp
      - target: 443
        published: "43923"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/vault2/BigAppData/NextCloud
        target: /var/www/html
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
  nextcloud-cron:
    cpu_shares: 10
    container_name: nextcloud-cron
    depends_on:
      nextcloud:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud
      - NEXTCLOUD_CRON_MINUTE_INTERVAL=10
    image: rcdailey/nextcloud-cronjob:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    ports: []
    devices: []
    cap_add: []
    command: []
    network_mode: bridge
    privileged: false
  nextcloud-db:
    cpu_shares: 90
    command:
      - postgres
    container_name: nextcloud-db
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=nextokcsdl
      - POSTGRES_USER=nextcloud
    hostname: nextcloud-db
    image: postgres:14.5
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
    ports:
      - target: 5432
        published: "5435"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/PostgreSQL-nextcloud
        target: /var/lib/postgresql/data
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
  index: /
  port_map: "43920"
  scheme: http
  store_app_id: Nextcloud
  title:
    custom: Nextcloud
``` 

Also, i have to say that nextcloud is one example, it happens to more container like Syncthing.
I'll give the compose file.

```yaml
name: syncthing
services:
  syncthing:
    cpu_shares: 90
    container_name: syncthing
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Andorra
    hostname: syncthing
    image: linuxserver/syncthing:latest
    labels:
      icon: https://icon.casaos.io/main/all/syncthing.png
    ports:
      - target: 8384
        published: "8384"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: udp
      - target: 21027
        published: "21027"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Syncthing/config
        target: /config
      - type: bind
        source: /mnt
        target: /data
    devices: []
    cap_add: []
    command: []
    networks:
      - syncthing
    privileged: false
networks:
  syncthing:
    name: syncthing
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/syncthing.png
  index: /
  port_map: "8384"
  scheme: http
  store_app_id: syncthing
  title:
    custom: Syncthing

``` 
The error is:

`getaddrinfo EAI_AGAIN`
