### ISSUE TITLE
[Alpha][Bug] Update Problem CasaOS 0.4.4

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#1259]
### What happened?

I install Gitea in CasaOS 0.4.4 and when i have to update the Gitea project with the function of CasaOS to update containers, i have encountered one problem. 

When the database name of the service is alphabetically first and the main project, like Gitea itself, is second. When you update, the function detects the first container which is the database container, but the issue is, the database is static because its image is a version specific tag so CasaOS detect that they are not update available and stops.

In summary, CasaOS not detect the second container, the main project, Gitea and don't update.  

I'll give the ComposeFile

```yaml
name: gitea
services:
  gitea:
    cpu_shares: 90
    container_name: Gitea
    depends_on:
      db:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_PASSWD=gitea
      - DB_TYPE=postgres
      - DB_USER=gitea
      - USER_GID=1000
      - USER_UID=1000
    image: gitea/gitea:latest
    labels:
      icon: https://icon.casaos.io/main/all/gitea.png
    ports:
      - target: 3000
        published: "15432"
        protocol: tcp
      - target: 22
        published: "15433"
        protocol: tcp
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /mnt/vault2/BigAppData/gitea
        target: /data
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
    devices: []
    cap_add: []
    command: []
    networks:
      - gitea
  db:
    cpu_shares: 90
    container_name: postgresql-gitea
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_USER=gitea
    image: postgres:14.5
    labels:
      icon: https://icon.casaos.io/main/all/gitea.png
    ports:
      - target: 5432
        published: "5432"
        protocol: tcp
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/PostgreSQLG
        target: /var/lib/postgresql/data
    devices: []
    cap_add: []
    command: []
    networks:
      - gitea
networks:
  gitea:
    name: gitea
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/gitea.png
  index: /
  port_map: "15432"
  scheme: http
  store_app_id: gitea
  title:
    custom: Gitea


```
