### ISSUE TITLE
[Bug] [Docker Compose] When a yaml has the 'privileged' tag, it doesn't matter if it's true or false, the container always starts as privileged=true

### ISSUE THREAD

**Issue by raphamotta** [IceWhaleTech/CasaOS#1264]
**Describe the bug**

Instaling an App thru custom install (Docker compose), when a yaml or code has the 'privileged' tag, it doesn't matter if it's true or false, the container always starts as privileged=true, unless if you disable on the privileged button 

**To Reproduce**

Per exemple, put the code on custom installation (Import -> Docker Compose):

```
name: openspeedtest
services:
  openspeedtest:
    deploy:
      resources:
        reservations:
          memory: "67108864"
        limits:
          memory: 23988M
    image: openspeedtest/latest:v0.0.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/OpenSpeedTest/icon.png
    ports:
      - target: 3000
        published: "3004"
        protocol: tcp
    restart: always
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: ""
    volumes: []
    devices: []
    cap_add: []
    command: []
    environment: []
    network_mode: bridge
    privileged: false
    container_name: ""
    cpu_shares: 90
```

You can see "privileged: false" but after save, you can see the privileged button active, and if you install like this the container will the privileged even if the code has it as false

> Steps to reproduce the behavior:

**Expected behavior**

privileged: false is privileged: false

**Desktop (please complete the following information):**

Teste on raspberry pi 3 and also in a ARM VPS on OCI
