### ISSUE TITLE
[Bug] I cannot update Nexcloud, "Update not avaliable"

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#1330]
**Describe the bug**

There is something wrong, some time ago in CasaOS version 0.4.4.4, there was a problem with the application update issue due to the order of the services, this is the issue, #1259.

But now it happens again, but the order of services is correct and this has started to happen since I upgraded to CasaOS version 0.4.4.1. 

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to Nextcloud App
2. Click on Update
4. No update avaliable.

**Expected behavior**

Nextcloud should have been updated to the new version.

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/18572939/d3ace0b0-6524-4bbb-8226-23506f96d7cb)

![image](https://github.com/IceWhaleTech/CasaOS/assets/18572939/97323211-a960-4f7b-bb62-da1b046bd77d)

![image](https://github.com/IceWhaleTech/CasaOS/assets/18572939/fd9d6e2b-efbf-48e4-89bd-e732792615ea)

![image](https://github.com/IceWhaleTech/CasaOS/assets/18572939/4e98aeb7-7318-4038-917b-0da50ba8a0c6)

**Desktop (please complete the following information):**

```
 - OS: Ubuntu 22.04 LTS
 - Browser Chrome
 - Version 115.0.5790.110 (Build oficial) (64 bits)
 - Docker version 24.0.5, build ced0996

```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-app-management
```
```log
ago 07 15:01:13 graves-vault casaos-app-management[6483]: 2023-08-07T15:01:13.624+0200        info        App does not have x-casaos extension - skipping        {"app": "jellyfin", "func": "service.(*ComposeApp).StoreInfo", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/compose_app.go", "line": 71}
ago 07 15:01:13 graves-vault casaos-app-management[6483]: 2023-08-07T15:01:13.627+0200        info        App does not have x-casaos extension - skipping        {"app": "nextcloud-db", "func": "service.(*ComposeApp).StoreInfo", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/compose_app.go", "line": 71}
ago 07 15:01:13 graves-vault casaos-app-management[6483]: 2023-08-07T15:01:13.627+0200        info        App does not have x-casaos extension - skipping        {"app": "nextcloud", "func": "service.(*ComposeApp).StoreInfo", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/compose_app.go", "line": 71}
ago 07 15:01:13 graves-vault casaos-app-management[6483]: 2023-08-07T15:01:13.627+0200        info        App does not have x-casaos extension - skipping        {"app": "nextcloud-cron", "func": "service.(*ComposeApp).StoreInfo", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/compose_app.go", "line": 71}
ago 07 15:01:13 graves-vault casaos-app-management[6483]: 2023-08-07T15:01:13.627+0200        info        app not found in any appstore        {"id": "Nextcloud", "func": "service.(*AppStoreManagement).ComposeApp", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/appstore_management.go", "line": 390}
ago 07 15:01:13 graves-vault casaos-app-management[6483]: 2023-08-07T15:01:13.627+0200        info        Using default appstore        {"func": "service.(*AppStoreManagement).ComposeApp", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/appstore_management.go", "line": 397}
ago 07 15:01:13 graves-vault casaos-app-management[6483]: 2023-08-07T15:01:13.627+0200        error        store compose app not found, thus no update available        {"storeAppID": "Nextcloud", "func": "service.(*ComposeApp).IsUpdateAvailable", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/compose_app.go", "line": 181}

```

**Additional context**

Yaml exported from Nexcloud CasaOS App
```yaml
name: nextcloud
services:
  nextcloud:
    cpu_shares: 90
    command:
      - apache2-foreground
    container_name: nextcloud
    depends_on:
      nextcloud-db:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - PHP_UPLOAD_LIMIT=512M
    image: nextcloud:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
    ports:
      - target: 80
        published: "43920"
        protocol: tcp
      - target: 443
        published: "43923"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/vault2/BigAppData/NextCloud
        target: /var/www/html
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
  nextcloud-cron:
    cpu_shares: 10
    container_name: nextcloud-cron
    depends_on:
      nextcloud:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - NEXTCLOUD_CONTAINER_NAME=nextcloud
      - NEXTCLOUD_CRON_MINUTE_INTERVAL=10
    image: rcdailey/nextcloud-cronjob:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    ports: []
    devices: []
    cap_add: []
    command: []
    network_mode: bridge
    privileged: false
  nextcloud-db:
    cpu_shares: 90
    command:
      - postgres
    container_name: nextcloud-db
    deploy:
      resources:
        limits:
          memory: 15859M
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=nextokcsdl
      - POSTGRES_USER=nextcloud
    hostname: nextcloud-db
    image: postgres:14.5
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
    ports:
      - target: 5432
        published: "5435"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/PostgreSQL-nextcloud
        target: /var/lib/postgresql/data
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/icon.png
  index: /
  port_map: "43920"
  scheme: http
  store_app_id: Nextcloud
  title:
    custom: Nextcloud
```
