### ISSUE TITLE
[Feature Request] Markdown support in AppStore UI

### ISSUE THREAD

**Issue by mr-manuel** [IceWhaleTech/CasaOS#1383]
**Describe the bug**
Markdown is only rendered for `x-casaos.tips.before_install` but not for `x-casaos.description.*` and `x-casaos.tagline.*`.

**To Reproduce**

1. Add markdown to the `docker-compose.yml`
2. Check how it gets rendered

**Expected behavior**
Markdown should be rendered.

**Screenshots**
![grafik](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/12592765/7da28f3b-77d0-4808-b95c-fd0962b28046)

**Additional context**
Relevant part of `docker-compose.yml`
```yml
...
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: mr-manuel
  category: Network
  description:
    en_us: |
      Traefik allows you to access multiple containers on the same IP via port HTTP/HTTP and hostnames. Since Traefik reads the Docker containers it automatically searches for an open port and makes it available.

      By default Traefik will use port `81` for `HTTP`, port `443` for `HTTPS` and port `8080` for the dashboard. If you want to use port `80` for `HTTP`, then you have first to change the WebUI port of CasaOS first under the settings in the top left menu. After deploying the container you can change the port mapping from `81` to `80`.

      Visit [Traefik Labs](https://traefik.io) for more details. Check the [documentation](https://doc.traefik.io/traefik/) for further settings.

      🚨 Note: This app will always be upgraded to the latest version. If you want to stay on Traefik `1.x` or `2.x` install `Traefik v1` or `Traefik v2`.
  developer: Traefik Labs
  icon: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Traefik/icon.png
  index: /dashboard/
  main: traefik
  port_map: "8080"
  project_url: https://github.com/mr-manuel/CasaOS-HomeAutomation-AppStore
  store_app_id: traefik
  tagline:
    en_us: |
      Traefik is the leading open-source reverse proxy and load balancer for HTTP and TCP-based applications that is easy, dynamic and full-featured.
  thumbnail: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Traefik/icon.png
  tips:
    before_install:
      en_us: |
        By default Traefik will use port `81` for `HTTP`, port `443` for `HTTPS` and port `8080` for the dashboard. If you want to use port `80` for `HTTP`, then you have first to change the WebUI port of CasaOS first under the settings in the top left menu. After deploying the container you can change the port mapping from `81` to `80`.

        Visit [Traefik Labs](https://traefik.io) for more details. Check the [documentation](https://doc.traefik.io/traefik/) for further settings.
  title:
    en_us: Traefik

```
