### ISSUE TITLE
[Bug] Volume mounts are not supported and get silently converted to bind mounts

### ISSUE THREAD

**Issue by deepybee** [IceWhaleTech/CasaOS#1595]
**Describe the bug**

When importing a Docker Compose YAML which contains a [volume mount](https://docs.docker.com/storage/volumes/) rather than a [bind mount](https://docs.docker.com/storage/bind-mounts/), CasaOS imports the YAML and starts the stack, but silently interprets the volume mount as a bind mount to the host machine, which gets a writable folder created on it at `/tmp/casaos-compose-app-<UUID>/'[object Object]'` when the stack is created.

This means that the user is forced to make all SMB / CIFS shares available to the whole host so that they can be used as bind mounts on services being deployed. This is a poor security practice as it means the host is constantly connected to remote machines it may have no business talking directly to.

It also means each share the host is connected to can only be reached with a single set of privileges (typically read/write); if volume mounts were supported properly they would allow different containers to connect to the same share with different user accounts and privileges set at the remote end, so one service might be read only where another connects to the same share with an account that has write access also. This can be worked around with a bunch of garbage filling up `/etc/fstab` on the host but that is a really ugly solution, especially when there are many shares and access rights to accommodate.

A better workaround in the meantime to this is to deploy Portainer from the app store and use it to deploy services which require access to shares using volume mounts (steps detailed at the bottom of this bug report). Unfortunately, this has the consequence of CasaOS showing the service as a legacy app that needs to be rebuilt, as shown in the screenshot below.

If the user clicks on the tile to import the app into CasaOS it breaks the volume mount upon creation of the new container, which gets created with a bind mount to the host's `/tmp` directory as described above.

**To Reproduce**

1. On the CasaOS main page click on `+`. 
2. Click on `Install a customized app`.
3. Click on the icon in the top right to import a config.
4. Paste the following YAML in the text box, replacing IPs, paths and credentials as necessary.

```
name: lidarr
services:
  lidarr:
    cpu_shares: 90
    command: []
    container_name: lidarr
    deploy:
      resources:
        limits:
          memory: 7801M
    environment:
      - DOCKER_MODS=linuxserver/mods:lidarr-flac2mp3
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    image: lscr.io/linuxserver/lidarr
    labels:
      icon: https://raw.githubusercontent.com/Lidarr/Lidarr/develop/Logo/256.png
    ports:
      - target: 8686
        published: "8686"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/config
        target: /config
      - type: bind
        source: /DATA/Media/Music
        target: /music
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: volume
        source: nas_mount
        target: /convert_paths
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
volumes:
  nas_mount:
    driver: local
    driver_opts:
      type: cifs
      device: "//10.0.0.100/share"
      o: "username=lidarr,password=5up3r53cr3tP455w0rd,uid=1000,gid=1000"
```

6. When the stack has spun up, log into the console of the container
7. run `ls -l /convert_paths` (to use the example above)

**Expected behavior**

The contents of the remote folder at `//10.0.0.100/share` is displayed.

**Actual behavior**

The empty contents of the folder at `/tmp/casaos-compose-app-<UUID>/'[object Object]'` on the host filesystem is displayed.

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/5628465/e31b2347-cdc3-45aa-86f6-d9533bbcb507)

**Desktop (please complete the following information):**

```
 - OS: CasaOS 0.4.4-3
 - Browser Any
 - Version Any
```

**Additional context**

To get a working volume mount the below can be done as a workaround:

1. Uninstall the previous service installation using the `Uninstall` option from the tile's context menu on the CasaOS main page. 
2. On the CasaOS main page click on the App Store tile.
3. Click on the Portainer tile and install as normal.
4. Click on the tile to open the Portainer UI.
5. Set an admin username and password and log in to Portainer.
6. Click on `Live Connect` to connect to the Docker socket.
7. Click on `Stacks`.
8. Click on `Add stack`.
9. Copy and paste the YAML above, amending IPs, paths and credentials as necessary.
10. Click on `Deploy the stack`
11. When the stack has spun up, log into the console of the container
12. run `ls -l /convert_paths` (to use the example above)
13. Observe the contents of the remote directory at `//10.0.0.100/share`.

I bought my Zimaboard a few weeks ago in November or December 2023.
