### ISSUE TITLE
[Bug] WebUI Compose failed to import `published` numeric types

### ISSUE THREAD

**Issue by Cp0204** [IceWhaleTech/CasaOS#1600]
**Describe the bug**

Importing using Docker Compose in the WebUI fails to match the port ports - published field when it is a numeric type, but works when it is a text type.

Although both types are compatible for installation using docker compose up -d, the numeric type should be used according to the port specification.

WebUI 中使用 Docker Compose 导入，当端口 ports - published 字段是数字类型时，会匹配失败，是文本类型时反而可以。

虽然两种类型使用 docker compose  up -d 都能兼容安装，但是按端口规范应该使用数字类型。

**To Reproduce**

Example:
举例：

The following import failed: 
以下导入失败：
```yaml
name: dockge
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    network_mode: bridge
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/$AppID/stacks
        target: /opt/stacks
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks
```

The following import was successful:
以下导入成功：
```yaml
name: dockge
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    network_mode: bridge
    ports:
      - target: 5001
        published: '5001'
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /app/data
      - type: bind
        source: /DATA/AppData/$AppID/stacks
        target: /opt/stacks
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks
```
