### ISSUE TITLE
Home Assistant Supervised

### ISSUE THREAD

**Issue by sdmorris1950** [IceWhaleTech/CasaOS#1678]
The App Store version of Home Assistant is for the Core version, which does not support Add-ons.

I would like to have an install for Home Assistant Supervised in the App Store.

**Comment by jchisholm59** [comment]
AFAIK no docker based HA instances support Supervised

**Comment by huizebruin** [comment]
and the version in the app store is old 2023.11
whit this i had the new and latest version installed.
```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
 ```
from -->   
https://www.home-assistant.io/installation/alternative/#docker-compose
