### ISSUE TITLE
ttrss服务构建后docker-proxy代理拒绝服务[Bug] 

### ISSUE THREAD

**Issue by joe07274** [IceWhaleTech/CasaOS#1698]
构建ttrss的compose文件:

```yaml
version: '3'

networks:
  ttrss:

services:
  ttrss:
    image: wangqiru/ttrss
    container_name: ttrss
    restart: always
    environment:
      - SELF_URL_PATH=http://192.168.0.253:181
      - DB_HOST=ttrss_db
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=ttrss
      - DB_PASS=ttrss
    ports:
      - "181:8081"
    depends_on:
      - ttrss_db
    networks:
      - ttrss

  ttrss_db:
    image: postgres
    container_name: ttrss-db
    restart: always
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - ttrs
```

构建后，服务能启动成功，
![image](https://github.com/IceWhaleTech/CasaOS/assets/4698688/19491a04-8dcb-4f24-af7b-fdd425a35630)
![image](https://github.com/IceWhaleTech/CasaOS/assets/4698688/89adfd03-f641-4d47-81c0-ca21e5b2fe1f)

日志打印也正常：
```text
ttrss-db  | The files belonging to this database system will be owned by user "postgres".
ttrss-db  | This user must also own the server process.
ttrss-db  | 
ttrss-db  | The database cluster will be initialized with locale "en_US.utf8".
ttrss-db  | The default database encoding has accordingly been set to "UTF8".
ttrss-db  | The default text search configuration will be set to "english".
ttrss-db  | 
ttrss-db  | Data page checksums are disabled.
ttrss-db  | 
ttrss-db  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
ttrss-db  | creating subdirectories ... ok
ttrss-db  | selecting dynamic shared memory implementation ... posix
ttrss-db  | selecting default max_connections ... 100
ttrss-db  | selecting default shared_buffers ... 128MB
ttrss-db  | selecting default time zone ... Etc/UTC
ttrss-db  | creating configuration files ... ok
ttrss-db  | running bootstrap script ... ok
ttrss-db  | performing post-bootstrap initialization ... ok
ttrss-db  | syncing data to disk ... ok
ttrss-db  | 
ttrss-db  | 
ttrss-db  | Success. You can now start the database server using:
ttrss-db  | 
ttrss-db  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
ttrss-db  | 
ttrss-db  | initdb: warning: enabling "trust" authentication for local connections
ttrss-db  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
ttrss-db  | waiting for server to start....2024-02-13 03:11:05.671 UTC [49] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
ttrss-db  | 2024-02-13 03:11:05.699 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ttrss-db  | 2024-02-13 03:11:05.784 UTC [52] LOG:  database system was shut down at 2024-02-13 03:10:58 UTC
ttrss-db  | 2024-02-13 03:11:05.817 UTC [49] LOG:  database system is ready to accept connections
ttrss-db  |  done
ttrss-db  | server started
ttrss-db  | CREATE DATABASE
ttrss-db  | 
ttrss-db  | 
ttrss-db  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
ttrss-db  | 
ttrss-db  | waiting for server to shut down...2024-02-13 03:11:07.384 UTC [49] LOG:  received fast shutdown request
ttrss-db  | .2024-02-13 03:11:07.423 UTC [49] LOG:  aborting any active transactions
ttrss-db  | 2024-02-13 03:11:07.428 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
ttrss-db  | 2024-02-13 03:11:07.429 UTC [50] LOG:  shutting down
ttrss-db  | 2024-02-13 03:11:07.482 UTC [50] LOG:  checkpoint starting: shutdown immediate
ttrss-db  | 2024-02-13 03:11:08.080 UTC [50] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.134 s, sync=0.325 s, total=0.651 s; sync files=301, longest=0.270 s, average=0.002 s; distance=4257 kB, estimate=4257 kB; lsn=0/1912FE0, redo lsn=0/1912FE0
ttrss-db  | 2024-02-13 03:11:08.094 UTC [49] LOG:  database system is shut down
ttrss-db  |  done
ttrss-db  | server stopped
ttrss-db  | 
ttrss-db  | PostgreSQL init process complete; ready for start up.
ttrss-db  | 
ttrss-db  | 2024-02-13 03:11:08.329 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
ttrss-db  | 2024-02-13 03:11:08.330 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ttrss-db  | 2024-02-13 03:11:08.330 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ttrss-db  | 2024-02-13 03:11:08.417 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ttrss-db  | 2024-02-13 03:11:08.520 UTC [65] LOG:  database system was shut down at 2024-02-13 03:11:08 UTC
ttrss-db  | 2024-02-13 03:11:08.566 UTC [1] LOG:  database system is ready to accept connections
ttrss-db  | 2024-02-13 03:11:09.357 UTC [74] ERROR:  relation "ttrss_version" does not exist at character 15
ttrss-db  | 2024-02-13 03:11:09.357 UTC [74] STATEMENT:  SELECT * FROM ttrss_version
ttrss-db  | 2024-02-13 03:16:08.586 UTC [63] LOG:  checkpoint starting: time
ttrss-db  | 2024-02-13 03:16:34.218 UTC [63] LOG:  checkpoint complete: wrote 252 buffers (1.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=25.431 s, sync=0.118 s, total=25.632 s; sync files=213, longest=0.083 s, average=0.001 s; distance=1334 kB, estimate=1334 kB; lsn=0/1A60A90, redo lsn=0/1A60A58
ttrss     | [03:11:09/52] Lock: update.lock
ttrss     | [03:11:09/52] Proceeding to update without confirmation.
ttrss     | [03:11:09/52] Loading base database schema...
ttrss     | [03:11:12/52] Migration finished, current version: 147
ttrss     | [03:11:12/59] Installing shutdown handlers
ttrss     | [03:11:12/59] Spawned child process with PID 64 for task 0.
ttrss     | [03:11:12/59] Spawned child process with PID 66 for task 1.
ttrss     | [03:11:13/67] Using task id 1
ttrss     | [03:11:13/67] Lock: update_daemon-66.lock
ttrss     | [03:11:13/65] Using task id 0
ttrss     | [03:11:13/65] Lock: update_daemon-64.lock
ttrss     | [03:11:13/67] Waiting before update (5)...
ttrss     | [03:11:13/65] Waiting before update (0)...
ttrss     | [03:11:13/65] Scheduled 0 feeds to update...
ttrss     | [03:11:13/65] Sending digests, batch of max 15 users, headline limit = 1000
ttrss     | [03:11:13/65] All done.
```

但是发现服务访问不通，
![image](https://github.com/IceWhaleTech/CasaOS/assets/4698688/d70c2645-788e-4ed6-85ba-07c06f6856c3)

把服务配置导出以后
```yaml
name: marvelous_rocco
services:
  ttrss:
    cpu_shares: 90
    command: []
    container_name: ttrss
    depends_on:
      ttrss_db:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 3793M
    environment:
      - DB_HOST=ttrss_db
      - DB_NAME=ttrss
      - DB_PASS=ttrss
      - DB_PORT=5432
      - DB_USER=ttrss
      - SELF_URL_PATH=http://192.168.0.253:181
    hostname: ttrss
    image: wangqiru/ttrss
    ports:
      - target: 181
        published: "8081"
        protocol: tcp
    restart: always
    volumes: []
    devices: []
    cap_add: []
    networks:
      - ttrss
    privileged: false
  ttrss_db:
    cpu_shares: 90
    command: []
    container_name: ttrss-db
    deploy:
      resources:
        limits:
          memory: 3793M
    environment:
      - POSTGRES_DB=ttrss
      - POSTGRES_PASSWORD=ttrss
      - POSTGRES_USER=ttrss
    hostname: ttrss-db
    image: postgres
    restart: always
    volumes:
      - type: bind
        source: /tmp/casaos-compose-app-4288198756/db
        target: /var/lib/postgresql/data
    ports: []
    devices: []
    cap_add: []
    networks:
      - ttrss
    privileged: false
networks:
  ttrss:
    name: ttrss
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: ""
  index: /
  port_map: "8081"
  scheme: http
  store_app_id: marvelous_rocco
  title:
    custom: ttrss
```

感觉是docker-proxy有哪个配置没有生效导致
