### ISSUE TITLE
自定义应用安装不了[Alpha][Bug] 

### ISSUE THREAD

**Issue by Rontalks** [IceWhaleTech/CasaOS#1713]
### What happened?

自定义应用安装不了，最后“安装”点不下去，点了好多次也没用，刷新首页之后会发现安装了一些乱七八糟却又打不开的东西，请问这是什么问题？

### Screenshots

![93dd7ecbb41e729d347cfcdc52f70cb2](https://github.com/IceWhaleTech/CasaOS/assets/74225244/4fa844b3-c059-47ce-b0c6-22dc88c37b68)

**Comment by 2273446670** [comment]
我很早前就遇到过这个问题，以为我配置的问题，结果很多人也都是这样，不知道为什么一直没人修，完全没办法部署新应用

**Comment by CorrectRoadH** [comment]
可以提供一下你自定义应用安装的docker compose yaml吗?

**Comment by CorrectRoadH** [comment]
如果是memos的话，推荐从应用商店下载。有时候无法安装可能是某一个参数错了。但是因为我们前端报错处理的不好，所以没有优雅的提示出来🤔

**Comment by komiblog** [comment]
same question

**Comment by DemonYibao** [comment]
我也遇到了同样问题，安装后，应用还在跑，就是casaos的APP显示有问题

**Comment by correctroadh** [comment]
> 我也遇到了同样问题，安装后，应用还在跑，就是casaos的APP显示有问题

是显示什么问题呀👀

**Comment by DemonYibao** [comment]
问题就是我安装的目标APP已经在运行了，但是casaos导航哪里就只显示有灰色随机应用

**Comment by azicen** [comment]
遇到同样的问题，点击安装没有反应。f12控制台一直刷同一个报错，但是等待一段时间容器能正常启动。casaos导航灰色，app名称为随机字符串，并且无法修改。确认写的docker compose yaml 没有问题，命令行使用一切正常。

**Comment by correctroadh** [comment]
> 遇到同样的问题，点击安装没有反应。f12控制台一直刷同一个报错，但是等待一段时间容器能正常启动。casaos导航灰色，app名称为随机字符串，并且无法修改。确认写的docker compose yaml 没有问题，命令行使用一切正常。

可以分享一下你的docker compose yaml吗? 👀

**Comment by azicen** [comment]
> > 遇到同样的问题，点击安装没有反应。 f12控制台一直刷同一个报错，但是等待一段时间容器能正常启动。 casaos导航灰色，app名称为随机字符串，并且无法修改。 确认写的docker compose yaml 没有问题，命令行使用一切正常。
> 
> 可以分享一下你的docker compose yaml吗? 👀

当然可以，这是其中之一，是一个Jellyfin的docker compose yaml

```yaml
version: '3.2'

services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Asia/Shanghai
      - HTTPS_PROXY=http://proxy.local:7890
      - HTTP_PROXY=http://proxy.local:7890
      - NO_PROXY=localhost,127.0.0.1,::1
      - PGID="0"
      - PUID="0"
    volumes:
      - /mnt/pool1/docker/file-service/jellyfin/config:/config
      - /mnt/pool1/media:/media
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
    restart: always
```

在这两天的使用中，我还注意到一个异常的情况，也许会对你们排查问题提供一些帮助。

如下图所示的docker compose导入步骤 ：

![{26E51FC8-A7BB-4175-B03D-E2C057E72CD3}](https://github.com/IceWhaleTech/CasaOS/assets/37183419/73820463-090e-4b07-9c70-50bb285699d0)

这样导入上述的yaml会出现异常的情况，导入时卷的主机路径发生错误。

![{8CFCCFDB-016F-483a-9161-137C9A558DB1}](https://github.com/IceWhaleTech/CasaOS/assets/37183419/2283d002-9d34-4d58-a420-38d9e4073e1d)

通常我需要将这些错误的卷路径点击(x)图表删除，重新手动添加，并且不调整内存限制与cpu限制的情况下，容器得以正常创建。
