### ISSUE TITLE
[Bug] compose import not detecting all containers

### ISSUE THREAD

**Issue by SX-9** [IceWhaleTech/CasaOS#1823]
**Describe the bug**

importing a compose file dint import all the containers in the file (only 1)

**To Reproduce**

1. import this docker compose:
```yaml
version: '3.9'

networks:
  guacamole_net:
    driver: bridge

services:
  guacd:
    container_name: guacamole_backend
    image: guacamole/guacd:1.5.3
    networks:
      guacamole_net:
    restart: always
    volumes:
      - /DATA/AppData/guacamole/drive:/drive:rw
      - /DATA/AppData/guacamole/record:/var/lib/guacamole/recordings:rw
postgres:
  container_name: guacamole_database
  environment:
    PGDATA: /var/lib/postgresql/data/guacamole
    POSTGRES_DB: guacamole_db
    POSTGRES_PASSWORD: pg-pw-1234
    POSTGRES_USER: internal
  image: postgres:15.0
  networks:
    guacamole_net:
  restart: always
  volumes:
    - /DATA/AppData/guacamole/init:/docker-entrypoint-initdb.d:ro
    - /DATA/AppData/guacamole/data:/var/lib/postgresql/data:rw

guacamole:
  container_name: guacamole_frontend
  depends_on:
    - guacd
    - postgres
  environment:
    GUACD_HOSTNAME: guacd
    POSTGRESQL_DATABASE: guacamole_db
    POSTGRESQL_HOSTNAME: postgres
    POSTGRESQL_PASSWORD: pg-pw-1234
    POSTGRESQL_USER: internal
    POSTGRESQL_AUTO_CREATE_ACCOUNTS: true
  image: guacamole/guacamole:1.5.3
  links:
    - guacd
  networks:
    - guacamole_net
  ports:
    - 8080:8080
  restart: always
  volumes:
    - /DATA/AppData/guacamole/drive:/drive:rw
    - /DATA/AppData/guacamole/record:/var/lib/guacamole/recordings
```

**Expected behavior**

imports all containers mentioned

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/90962949/11f7b638-88d2-4e01-a431-0f075c1f728d)
![Screenshot from 2024-05-15 07-45-04](https://github.com/IceWhaleTech/CasaOS/assets/90962949/f1cbdc7f-76a7-40d8-abcb-45eadd4061f0)
![Screenshot from 2024-05-15 07-45-16](https://github.com/IceWhaleTech/CasaOS/assets/90962949/be74fe29-e190-4871-9a01-9f18e1a1e9c7)
![Screenshot from 2024-05-15 07-45-26](https://github.com/IceWhaleTech/CasaOS/assets/90962949/3a3acd41-4983-471c-bfde-4d74cfdbff4f)
