### ISSUE TITLE
[Bug] WEB 导入 Compose 代码的时候映射文件夹路径显示不全

### ISSUE THREAD

**Issue by iibeibei** [IceWhaleTech/CasaOS#2041]
很早之前今年3月份的时候就有人在 https://github.com/IceWhaleTech/CasaOS/issues/1713 提到这个问题，到现在大半年过去了也更新了好几个版本都没有看到有修复

可能是容器有映射 /config 这个路径的比较少，影响范围可能不大，索性就自己找下原因，希望官方能修复一下
只在映射的容器路径是 /config 的时候会触发这个 BUG

![_20241030105237.png](https://s2.loli.net/2024/10/30/aSmB6nLj1JXNDo4.jpg)

查看解析函数 volumeAutoCheck 发现是 appName 没有传值

![_20241030110033.png](https://s2.loli.net/2024/10/30/9WzFlqwg73BNrbO.jpg)

往上查看调用发现是 composeServicesItem.label 没有定义

![_20241030105529.png](https://s2.loli.net/2024/10/30/iBepMLR7m3xXW2P.jpg)

在 CasaOS v0.4.13 当前最新版复现 Compose  代码 

```
name: beibei-baidunetdisk
services:
  baidunetdisk:
    image: johngong/baidunetdisk:latest
    volumes:
      - /DATA/AppData/baidunetdisk/config:/config
    network_mode: bridge
    privileged: false
    restart: unless-stopped
```
