### ISSUE TITLE
[Bug] Environment variable will omitt "=" at the last for base64 content

### ISSUE THREAD

**Issue by mcdullmedia** [IceWhaleTech/CasaOS#2201]
**Describe the bug**

> A clear and concise description of what the bug is.
For whatever import method, docker compose, yaml save, etc, if the Envrionment varible is base64, i.e. with "=" at the end, it will be timmed in GUI.

**To Reproduce**

> Steps to reproduce the behavior:

After import, the "=" will disappear

**Expected behavior**

The varible should be exactly the same as the import text

**Desktop (please complete the following information):**

```
 - OS: linux
 - Browser chrome
 - Version latest
```

**System Time**

> Run `timedatectl` and share the output

```
              Local time: Thu 2025-03-20 01:47:55 HKT
           Universal time: Wed 2025-03-19 17:47:55 UTC
                 RTC time: Wed 2025-03-19 17:47:56
                Time zone: Asia/Hong_Kong (HKT, +0800)
System clock synchronized: yes
              NTP service: n/a
          RTC in local TZ: no

```

**Logs**

> Run following command to collect corresponding logs:

not required

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by guquan-lengyue** [comment]
my docker-compose.yaml as 
```yaml
version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      params=: V1ZoT2ExbFlUbXROVkVsNg==
      params2=: V1ZoT2ExbFlUbXROVkVsNg==
```
my import setting ui as
![Image](https://github.com/user-attachments/assets/e0152f7e-6bb1-47c5-9fcf-e489dd1fe565)

I cant reproduce your result, can you share your docker-compose file and import result screenshots?
