### ISSUE TITLE
Can you add WeddingShare

To the store.

### ISSUE THREAD

**Issue by Chaitanya-Lad** [IceWhaleTech/CasaOS#2277]
Cirx08/WeddingShare this is the app i need to use for personal use can you guys help me with installation or add it to the store.

Thanks you.

**Comment by DURUII** [comment]
Before we add it to the store, you can try installing it as a custom Docker container app:

1. Click the '+' icon → 'Install a customized app'.
2. Click the import icon (top right) and paste the following Docker Compose:

```yaml
services:
  wedding-share:
    container_name: WeddingShare
    image: cirx08/wedding_share:latest
    ports:
      - '${HTTP_PORT:-8080}:5000/tcp'
    environment:
      TITLE: 'WeddingShare'
      ACCOUNT_OWNER_USERNAME: 'admin'
      ACCOUNT_OWNER_PASSWORD: 'admin'
      DATABASE_TYPE: 'sqlite'
      ENCRYPTION_KEY: 'ChangeMe'
      ENCRYPTION_SALT: 'ChangeMe'
    volumes:
      - data-volume-config:/app/config
      - data-volume-thumbnails:/app/wwwroot/thumbnails
      - data-volume-uploads:/app/wwwroot/uploads
      - data-volume-custom-resources:/app/wwwroot/custom_resources
    network_mode: bridge
    hostname: wedding-share
    restart: always

volumes:
  data-volume-config:
    name: WeddingShare-Config
  data-volume-thumbnails:
    name: WeddingShare-Thumbnails
  data-volume-uploads:
    name: WeddingShare-Uploads
  data-volume-custom-resources:
    name: WeddingShare-CustomResources
```

3. Click **Submit**, fill in *Title*, *Container port* and *Web UI port* (e.g. 9999), then click **Install**.

It should work.
