### ISSUE TITLE
[App Request]: Qinglong

### ISSUE THREAD

**Issue by JohnGuan** [IceWhaleTech/CasaOS#436]
### App Information

- Name: Qinglong
- Short Description: Scheduled task management dashboard supporting python3, javaScript, shell, typescript
- GitHub Repository: https://github.com/whyour/qinglong
- Docker Image: whyour/qinglong

### Why do you want this app?

As an online shopper, shopping platforms (like JD.com) often have activities like signing up for coupons. There are a lot of open source automation scripts written by authors to help me with such tasks to get coupons automatically. Many of them support using Qinglong to automate updates and runs.

### Additional information?

```
version: '2'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - ./data:/ql/data  # config files
    ports:
      - "0.0.0.0:5700:5700"  # webui port
    restart: unless-stopped
```
