### ISSUE TITLE
Onion services support

### ISSUE THREAD

**Issue by EthraZa** [IceWhaleTech/CasaOS#573]
Looks like CasaOS is missing a very cool feature found on projects like Umbrel and Citadel that allow us to access our services online in a very secure way via the Tor network.

This is the [Tor Onion Services](https://support.torproject.org/glossary/onion-services/) (formerly known as “[hidden services](https://support.torproject.org/glossary/hidden-services)”).

It seems It could be implemented on bare bones, like [Home Assistant suggests](https://www.home-assistant.io/blog/2017/11/12/tor/) or as a docker app like ([docker-tor-hidden-service](https://github.com/cmehay/docker-tor-hidden-service) or [onionize-docker](https://github.com/torservers/onionize-docker) for example).

For what I can see, the benefits of CasaOS implementing it as a core service is to be able to better control it and auto route every app enabled via the onion network.

Hope you guys can take a look at it.

**Comment by ETWang1991** [comment]
We got it, Future version support

**Comment by EthraZa** [comment]
Wow, that's awesome!
Does CasaOS have a roadmap or ETA site?

**Comment by EthraZa** [comment]
Just my 2c.
I made a test with [onionize-docker](https://github.com/torservers/onionize-docker) and it works like a charm.

tst\docker-compose.yml
```yml
version: '3'
services:

  onionize:
    image: torservers/onionize
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - bridge

  web:
    image: yeasy/simple-web:latest
    environment:
      - ONIONSERVICE_NAME=app
    ports:
      - 80:80
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
```
run:
```php
$ docker-compose up -d
Running ...

$ docker exec tst-onionize-1 cat /var/lib/tor/onion_services/app/hostname
xyz.onion
```
Open http://xyz.onion in Brave Tor Window or Tor Browser and profit.
