### ISSUE TITLE
1个建议 和1个BUG

### ISSUE THREAD

**Issue by curtisrecords** [IceWhaleTech/CasaOS#611]
- 之前有用过其他的类似于 CasaOS 的开源产品 后来留在 CasaOS 里面的原因是可以支持 Docker CLI 的导入 Docker Compose 的导入 这个我感觉很好用 | 非常感谢 CasaOS 团队的开源贡献 OvO
---
1. 但是目前图形端导入好像暂时不支持docker compose里面创建volumes 例如下面这个yml范例：
```yml
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
```
- 其中最下面的 volumes 并不能被很好的识别。
---
2. 目前我使用CasaOS的环境是PVE下虚拟了一个Ubuntu 然后再Ubuntu里面跑了个CasaOS (官方安装的脚本) 因为自己对LXC还不太熟悉.. 所以就跑到系统里装了 目前PVE的磁盘是lvm-thin 扩容12GB之后发现在Web端的这个地方（**存储空间小部件**）
![image](https://user-images.githubusercontent.com/71839629/196723527-d7cf62fd-e7a6-430e-8f30-b96e4b87e22c.png)
实际显示的是 docker overlay 的容量 并非整个磁盘的容量
```bash
root@curtisasia:~# df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              183M  3.4M  180M   2% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   15G   11G  3.2G  78% /
tmpfs                              915M     0  915M   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  127M  1.7G   7% /boot
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/df4810e36161eadfa9b32ee4e0af207308d782df2860877a2346b521675ee76b/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/ca707ddce2ec596ebb434bc155b656116c580536e9dd1e89181e40e2e40d7516/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/0dcd42fc00046ed15bbba7fd57cad21e734b2e814fd98d9300ede07921c4aaa2/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/5ab12f28f711c4f2e9dab871a0326a5c4d74397b88aa7d7a7327ffd337835868/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/ec11e72ec71c2a2af102df4b24f350f8105c61455a8355f1f5e62e5921ef9a93/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/ca38d1016ac0f19100586a891ad734bb2c51cb267bc7f5c10920c5d3a5bab12d/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/89f4c9a6004862ba0927c6da8513d133aa74beb11486375d5871bb93a7ba5e94/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/d012938e6ebcaeac77261e514aa66a57dd544986fe41afe5da0b00683e24cbfd/merged
overlay                             15G   11G  3.2G  78% /var/lib/docker/overlay2/27d41e868eb8eb2cb528a55d53781a831851caf027eac8e48457cd44feba904f/merged
tmpfs                              187M  4.0K  187M   1% /run/user/1000

root@curtisasia:~# lsblk
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0                       7:0    0 79.9M  1 loop /snap/lxd/22923
loop1                       7:1    0  103M  1 loop /snap/lxd/23541
loop2                       7:2    0   62M  1 loop /snap/core20/1587
loop3                       7:3    0 63.2M  1 loop /snap/core20/1623
loop4                       7:4    0   48M  1 loop /snap/snapd/17336
loop5                       7:5    0   48M  1 loop /snap/snapd/17029
sda                         8:0    0   50G  0 disk
├─sda1                      8:1    0    1M  0 part
├─sda2                      8:2    0    2G  0 part /boot
└─sda3                      8:3    0   30G  0 part
  └─ubuntu--vg-ubuntu--lv 253:0    0   15G  0 lvm  /
sr0                        11:0    1 1024M  0 rom
```
扩容之后的硬盘在Web端的 **存储空间管理器内** 是完全可以正常识别的 请问docker这个应该怎么修改overlay才可以让web端的 **存储空间小部件** 显示出正确的磁盘容量呢 清理其他的unuse docker volume么
