### ISSUE TITLE
[App Request] Wireguard-UI

### ISSUE THREAD

**Issue by mojothemonkey2** [IceWhaleTech/CasaOS#737]
### App Information

- Name: Wireguard-UI
- Short Description: WebUI for confirguring Wireguard
- Official Website: https://hub.docker.com/r/ngoduykhanh/wireguard-ui
- GitHub Repository: https://github.com/ngoduykhanh/wireguard-ui
- Docker Image: ngoduykhanh/wireguard-ui:latest

### Why do you want this app?

Helps users easily manage Wireguard config.
Does a very similar job the the helper script https://github.com/angristan/wireguard-install
But all through a nice WebUI.

Note: this is NOT running wireguard itself, it just manages the config (for both server and clients).
You would want to install wireguard directly on the host.
And there is suggestion how to create a service to watch & restart wireguard service on config changes.

### Additional information?

Working docker compose:
```
version: "3"
services:
  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: Wireguard-UI
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - WGUI_USERNAME=casaos
      - WGUI_PASSWORD=casaos
    volumes:
      - /DATA/AppData/WireguardUI:/app/db
      - /etc/wireguard:/etc/wireguard  #we modify the host config
```
Port is fixed to 5000.
It does work in briged mode, apart from the "Status" page, for connected peer info. As this needs host network + NET_ADMIN.

There is also an arm version of the image: `ngoduykhanh/wireguard-ui:latest-arm64`
(not sure if we can make this a selectable / automated option from CasaOS appstore).

**Comment by mojothemonkey2** [comment]
I've submitted a feature to wireguard-ui repo - so that it can manage Wireguard interface restarts automatically.
Which has been built and pushed in latest image.
So this can be used with updated docker compose, to make life even easier:
```
version: "3"
services:
  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: Wireguard-UI
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - WGUI_USERNAME=casaos
      - WGUI_PASSWORD=casaos
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    volumes:
      - /DATA/AppData/WireguardUI:/app/db
      - /etc/wireguard:/etc/wireguard
    restart: unless-stopped
```

**Comment by mojothemonkey2** [comment]
or, an alternative wireguard UI..

wg-easy
https://github.com/WeeJeWel/wg-easy

this UI has all the detail nicely shown on one page. I prefer it over wireguard-ui above.
it also does automatic restart of wireguard on changes.
but it lacks UI for configuring server-side settings that wireguard-ui has. instead you have to add as docker envs, which requires a bit of knowledge.
in particular the WG_HOST (for public ip). needs to be set. whilst wireguard-ui figures out your public ip automatically.
so hard to say which is ultimately the best option.

```
version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=<my public ip>
      - WG_PORT=51820 # public port, for clients
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /DATA/AppData/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"  # wireguard
      - "31000:51821/tcp"  # web ui
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
