### ISSUE TITLE
[App Request] docker-emulatorjs & Uptime Kuma

### ISSUE THREAD

**Issue by kent79** [IceWhaleTech/CasaOS#784]
### App Information

- Name: 
- Short Description: 
- Official Website: 
- GitHub Repository: 
- Docker Image:

**Comment by mojothemonkey2** [comment]
emulatorjs

great fun this, been playing all x-mas :D
and great idea too - fire up the docker; add some roms. then can play the games on any device in the household with a good browser.

website https://www.emulatorjs.com/
docker https://github.com/linuxserver/docker-emulatorjs
github https://github.com/EmulatorJS/EmulatorJS

eg working docker-compose:
```
---
version: "2.1"
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /DATA/AppData/emulatorjs/config:/config
      - /DATA/AppData/emulatorjs/data:/data
    ports:
      - 31001:3000 # management back end
      - 31000:80     # emulation front end
    restart: unless-stopped
```
