### ISSUE TITLE
Snippet-box

### ISSUE THREAD

**Issue by Virgus** [IceWhaleTech/CasaOS#848]
### App Information

- Name: Snippet-box
- Short Description: Personal Snippets Codes Repository
- GitHub Repository: https://github.com/pawelmalak/snippet-box
- Docker Image: pawelmalak/snippet-box:arm

### Why do you want this app?

The Docker image installs correctly via command line.

When I try to import to CasaOS the procedure fails and then I find in portainer that a second container gets created and nothing works any more. If I keep the app without importing it in CasaOS then it continues to work.

I'd love to access it from CasaOS GUI, does anybody know what could I do to troubleshoot the issue ?

Thanks,
V.

### Additional information?

Important to use the :arm tag to get it installed on RPIs or other ARM SBCs.

**Comment by CosmoFox** [comment]
Yeah! It`s nice app! But do not add only ARM version

**Comment by Virgus** [comment]
> Yeah! It`s nice app! But do not add only ARM version

The non-arm version is specified with the :latest tag. That's the easy part. The tricky part for me is to understand why the app "breaks" when I add it manually to the GUI. It would be enough to fix this and the app could be manually installed easily,

For completeness here the docker-compose.yml content I'm using:

```
version: '3'
services:
  snippet-box:
#    image: pawelmalak/snippet-box:latest
    image: pawelmalak/snippet-box:arm
    container_name: snippet-box
    volumes:
      - /DATA/AppData/snippet-box/data:/app/data
    ports:
      - 5000:5000
    restart: unless-stopped

```
